#!/bin/sh
# shellcheck disable=SC2155
export PATH="$PATH:$(find ~/.local/bin -type d | paste -sd ':' -)"

if [ -f "$HOME/.env" ]; then
  export $(grep -v '^#' "$HOME/.env" | xargs)
fi

# Default Programs:
export EDITOR="nvim"
export TERMINAL="org.alacritty"
# export BROWSER="librewolf.desktop"

# ~/ Clean-up:
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export GOPATH="$XDG_DATA_HOME/go"
export GOMODCACHE="$XDG_CACHE_HOME/go/mod"
export PATH=$PATH:$GOPATH/bin
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"
export TINYTEX="$XDG_DATA_HOME/TinyTeX"
export NVM_DIR="$XDG_DATA_HOME/nvm"
export RUSTUP_HOME="$XDG_CONFIG_HOME/rustup"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export PATH="$CARGO_HOME/bin:$PATH"
export GIT_CONFIG_GLOBAL="$XDG_CONFIG_HOME/git/config"
export VISIDATA_DIR="$XDG_DATA_HOME/visidata"

## aws
export AWS_SHARED_CREDENTIALS_FILE="$XDG_CONFIG_HOME/aws/credentials"
export AWS_CONFIG_FILE="$XDG_CONFIG_HOME/aws/config"

## Python
export IPYTHONDIR="$XDG_CONFIG_HOME/ipython"
export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/pythonrc"
export MPLCONFIGDIR="$XDG_CONFIG_HOME/matplotlib"
export JUPYTER_CONFIG_DIR="$HOME/.config/jupyter"

## Homebrew
export PATH="/opt/homebrew/bin:$PATH"
export HOMEBREW_NO_AUTO_UPDATE=1

## History files:
export WGET_HIST="$XDG_DATA_HOME/wget-hsts"
export SQLITE_HISTORY="$XDG_DATA_HOME/sqlite_history"
export PSQL_HISTORY="$XDG_DATA_HOME/psql_history"
export HISTFILE="$XDG_DATA_HOME/zsh_history"

# Paths (X220)
# export PATH="$HOME/.local/bin/scripts:$PATH"
# export PATH="$HOME/.local/bin/scripts/statusbar:$PATH"

# Export other program settings
## ls enable directory color:
export CLICOLOR=1
export LSCOLORS=gxfxcxdxbxegedabagacad
## Enable man syntax highlighting
export LESS_TERMCAP_mb=$'\e[1;32m'
export LESS_TERMCAP_md=$'\e[1;32m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[01;33m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[1;4;31m'
