#!/bin/sh
# shellcheck disable=SC2155

if [ -f "$HOME/.env" ]; then
  export $(grep -v '^#' "$HOME/.env" | xargs)
fi

# Default Programs:
export EDITOR="nvim"
export TERMINAL="com.mitchellh.ghostty"
# export BROWSER="librewolf.desktop"


# ~/ Clean-up:
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export GOPATH="$XDG_DATA_HOME/go"
export GOMODCACHE="$XDG_CACHE_HOME/go/mod"
export PATH=$PATH:$GOPATH/bin
export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/pythonrc"
export SQLITE_HISTORY="$XDG_DATA_HOME/sqlite_history"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"
export IPYTHONDIR="$XDG_CONFIG_HOME/ipython"
export TINYTEX="$XDG_DATA_HOME/TinyTeX"
export NVM_DIR="$XDG_CONFIG_HOME/nvm"


# Export other program settings
## ls enable directory color:
export CLICOLOR=1
export LSCOLORS=gxfxcxdxbxegedabagacad
## Enable man syntax highlighting
export LESS_TERMCAP_mb=$'\e[1;32m'
export LESS_TERMCAP_md=$'\e[1;32m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[01;33m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[1;4;31m'

# Start Hyprland on login
[[ -z $DISPLAY && $(tty) = /dev/tty1 ]] && exec Hyprland
