[manager]
show_hidden = true

[opener]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
]
edit = [
	{ run = '$EDITOR "$@"', block = true, for = "unix" },
	{ run = "%EDITOR% %*",  block = true, for = "windows" },
]

[preview]
max_height = 10000
max_width = 10000
image_filter = "nearest"
image_quality = 50

[folders]
Camera = { sort_by = "modified", sort_reverse = true }
Pictures = { sort_by = "modified", sort_reverse = true }
