#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

# xrandr --dpi 96		# Set DPI. User may want to use a larger number for larger screens.
# setbg &			# set the background with the `setbg` script

setxkbmap -layout gb
export-vars
~/.fehbg
xrdb ~/.config/x11/.Xresources
# dwmblocks &
# dunst &
# picom &

# # xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup

autostart="dunst dwmblocks unclutter picom"

for program in $autostart; do
	pidof -sx "$program" || "$program" &
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
